### ISSUE TITLE
[BUG]: `fatal: protocol '"https' is not supported`

### ISSUE THREAD

**Issue by marendowski** [gamemaker1/yeet#10]
## Describe the bug

When trying to install something from AUR `fatal: protocol '"https' is not supported` is shown. It doesn't occurs when installing something from official repositories.

## To Reproduce

1. For example type `yeet -S bashtop-git`
2. See error `fatal: protocol '"https' is not supported`

## Expected behavior

Work as expected.

## Screenshots

![image](https://github.com/gamemaker1/yeet/assets/37738748/c0dbf5c0-9680-444b-9b43-9d13b8e4b375)

## Versions (please complete the following information):

- 0.5.0

Really awesome wrapper, but the only bad thing about it is this AUR problem.

**Comment by gamemaker1** [comment]
Hi,

This seems to be occurring because the code adds double quotes to the variable it reads from the config file, which is already in double quotes.

I'll try fixing this tomorrow morning. Till then, could you please try to remove the double quotes surrounding the value of `AUR_BASE_URL` from the config file?

Regards,
Vedant

**Comment by marendowski** [comment]
Hi! I tried deleting them in all `yeet` source files (in `git clone --quiet ...` statements) and then running `makepkg -sfcCi --skipinteg` (to skip validity check), but error occurred. Don't know whether I did something wrong, will try again.

**Comment by gamemaker1** [comment]
I just released v0.5.1 with a fix for this, please let me know if you still face the issue!

**Comment by marendowski** [comment]
Great! It's working now! Could you update AUR and install script?

**Comment by gamemaker1** [comment]
I did update the AUR package, the install script should automatically pickup the latest version.
