### ISSUE TITLE
[FEAT]: Install/remove packages even if some are not found

### ISSUE THREAD

**Issue by marendowski** [gamemaker1/yeet#11]
## Is your feature request related to a problem?

On Arch Linux when using e.g `yeet -S package-name w3m w3m-img` package `w3m` is the real one and then is shown error `ERR Package package-name not found!`. Similar for `-R` option. But when trying `yeet -S w3m w3m-img` it installs `w3m` and then shows error `ERR Package w3m-img not found!`.

## Describe the solution you'd like

I'd like it to work in a way that makes all packages independent, will check if they exist, install/remove them separately and then at the end show errors if some of them don't exist.

I think it's the best solution when you don't remember exactly if you installed the `git`, `bin` or other version and have a few programs to install/remove in one go.

### Side note

I'd like to take a moment to just appreciate how this whole project looks and feels professional and well made, the program also works great.

**Comment by gamemaker1** [comment]
This sounds like a good idea, I'll try releasing it as soon as possible.

Also, thank you so much for the appreciation!

**Comment by gamemaker1** [comment]
Released v0.6.0 with this fix :)
