### ISSUE TITLE
[FEAT]: `--noconfirm` option?

### ISSUE THREAD

**Issue by marendowski** [gamemaker1/yeet#12]
## Is your feature request related to a problem?

I'm replacing `paru` with `yeet` in my dotfiles install script and would like it to install everything without user needing to accept every install.

## Describe the solution you'd like

A `--noconfirm` option that works like in `paru` (installs/removes everything without user's intervention).

**Comment by marendowski** [comment]
Sorry for me asking for things constantly, I just miss these features from `paru`.

**Comment by gamemaker1** [comment]
Please don't apologise, it's great that you're doing this: it helps make yeet better!

**Comment by gamemaker1** [comment]
Released v0.6.0 with this feature!
