### ISSUE TITLE
[BUG]: `NO_CONFIRM` works partially

### ISSUE THREAD

**Issue by marendowski** [gamemaker1/yeet#13]
## Describe the bug

`NO_CONFIRM` makes building option automatic, but doesn't make installing/removing packages through `pacman` automatic (although reinstalling is automatic).

## To Reproduce

1. Set env. variable `export NO_CONFIRM=true`.
2. Try to install something.
3. See choice to proceed with installation.

## Expected behavior

It skips the `proceed with installation` choice and installs/removes packages.

## Versions (please complete the following information):

- Yeet Version (type `yeet --help` to see it): 0.6.0

**Comment by marendowski** [comment]
Okay I achieved it by adding the `yes` e.g. `yes '' | yeet -S $i` in loop. But I think it need to patched anyway.

**Comment by gamemaker1** [comment]
Fixed in v0.6.1, sorry for the late reply :(
