### ISSUE TITLE
[FEAT]: Add numbering to search

### ISSUE THREAD

**Issue by marendowski** [gamemaker1/yeet#14]
## Is your feature request related to a problem?

When searching for a package you may encounter e.g. 5 packages that have a long name and have to install them.

## Describe the solution you'd like

Numbering for search. When you search for something, every returned package has a number. User then can type a number assigned to this package to add it OR can type its name.

But would this just add number e.g. `12` to install? No, because it would install only numbers that are sole and without any letter. But it would accept packages that have number at the beginning of their name e.g. `9base`.

The minimal search word length for `package-query` is 3 letters (before segfault), so you could e.g. search for `fir` and this would return (only my guess, because I didn't want to count them) around 500 results? But still, there are ONLY one packages (from my search) that is a number only: [1337](https://aur.archlinux.org/packages/1337). So this edge case could (but probably won't) be used to install package `1337` instead of 1337th.

**Comment by gamemaker1** [comment]
Hi,

I'd love to add this feature, but it does involve a lot of work that I don't have time for right now. Sorry about that :/

If you wish to create a PR, I'd be more than happy to review and get it merged.

Regards

**Comment by marendowski** [comment]
Hi, thanks for the reply. I understand, and also have a lot of work at the moment. I'll give it a try in some time.

**Comment by marendowski** [comment]
I'm working on it and it seems that typing `git` gives too many results, and `fir` gives 1636 (tested with `paru`). So I'll try doing it in a way that first will be searching for example for 20th package and then for the string `20`, and will choose only one of them. In that way when there are 1000+ results and a package `1337`, it will install only 1337th, but when results are 10 and the package `1337` is among them, then it will install it, because there are not enough results (duh).

**Comment by marendowski** [comment]
So it must:
1. Call package-query for a name
2. Loop over every package
3. Print this package number and info
4. Add this package to an array of packages
5. Go to 2.
6. Ask user for a number or a name
7. User enters something
8. First check if its a sole number e.g. 20, if is, then go to this index, and add corresponding element to install
9. Second check if its a name (which can start with a number e.g. 9base), if is, then loop over every element in the array (ugh), search for this name, and add corresponding element to install

Now I understand why `paru` developers didn't add string-based searching in it. Consider not implementing it lol.

**Comment by marendowski** [comment]
Okay, in my [repo](https://github.com/piotr-marendowski/yeet/tree/feature) I have working numbering with the search, and a Makefile to easily install/uninstall yeet, but Makefile loops on building `package-query`, and results are now numbered, but lost their color due to the use of `awk`, check README for added dependencies.

**Comment by gamemaker1** [comment]
I will take a look, thanks for the great work!

**Comment by marendowski** [comment]
Now it looks like it with some ANSI escape sequences:
![image](https://github.com/gamemaker1/yeet/assets/37738748/39724b65-73fa-48b5-ac21-b61f522556e4)

Made the results bold and green, can't really separate them to make it look like the original. I'm thinking about dropping the popularity and version or making it an opt-in option via config.

**Comment by marendowski** [comment]
New look:

![image](https://github.com/gamemaker1/yeet/assets/37738748/a5a3eef7-bcad-430c-9303-44510e15e437)

I deleted "Is out of date" and popularity flags, when coloring via `package-query`, to preserve fields for description. I tried other colors, but green fits right there perfect.

And of course there is also a downfall - we basically can't show if package is installed etc. on the system, because it requires another `awk` call, and that would kill the performance.

**Comment by gamemaker1** [comment]
Hi!

Sorry for the late replies, and thank you so much for the great work so far. I took some time to review the changes, and I had a few suggestions:

1. Instead of adding the color manually, you could pass the `--color` option to `package-query`, so it preserves the colors even when its output is piped to another command. Something like this:

```diff
        # Search the sync repos and AUR
-       package-query --rsort=p -sSA "$(join_by ' ' $search_terms)"
+       package-query --color --rsort pop -sSA \
+               "$(join_by ' ' $search_terms)" | sed '$ d' | \
+               # Print the package number on every odd line (%d is the number, %s is the package info)
+               awk 'NR % 2 == 1 { printf "\033[1m%d.\033[0m %s\n", (NR+1)/2, $0; } NR % 2 == 0 { print $0; }'
```

2. I didn't understand how the array slicing works in the `searchinstall` function, on [line 630](https://github.com/piotr-marendowski/yeet/blob/774928d38432ffd2df2bbe11b7cbd88427cdcd5d/yeet#L630-L631). Moreover, it also seems to include two packages when only one number was entered. Instead, could we use something like this:

```diff
-       # Install the selected packages
-       install_packages $REPLY
+       # Decrement every number to install
+       for ((i=0; i<${#numbers[@]}; i++)); do
+               # Install the selected packages only
+               idx=$((${numbers[i]}-1))
+               install_packages ${programs[idx]}
+       done
 }
```

**Comment by gamemaker1** [comment]
Also, could you please open a PR against the main branch so it becomes easier for me to review the changes? Thanks :)
