### ISSUE TITLE
[BUG]: Install script doesn't work

### ISSUE THREAD

**Issue by marendowski** [gamemaker1/yeet#18]
## Describe the bug

Does nothing.

![image](https://github.com/gamemaker1/yeet/assets/37738748/6712f43d-7a28-412f-8599-9898b63ee97f)

**Comment by gamemaker1** [comment]
Turns out curl doesn't follow redirects by default, could you please try using `curl -L https://...` instead? Or replace `raw.github.com` with `raw.githubusercontent.com` to skip the redirect.

**Comment by marendowski** [comment]
Well, I have yeet installed so I don't know if it should work that way

![image](https://github.com/gamemaker1/yeet/assets/37738748/1d427f5b-fe8c-4c3b-9262-5f2b1ca326fe)

**Comment by gamemaker1** [comment]
I think that's because you've installed it via `make install` instead of pacman.

**Comment by marendowski** [comment]
Can't it overwrite the current version? I think that's a default for programs out there.
